### ISSUE TITLE
Unable to start receiver com.google.android.gms.gcm.GcmReceiver

### ISSUE THREAD

**Issue by ghost1372** [pusheco/android-studio-sample#1]
سلام طبق راهنما پیش رفتم ولی موقع دریافت پیغام برنامه کرش میکنه
Unable to start receiver com.google.android.gms.gcm.GcmReceiver
مشکل کجاست؟

**Comment by mhahmadip** [comment]
به نام خدا
سلام دوست عزیز
خوشحالیم که از سرویس پوشه استفاده می کنید.
برای تست و اجرای اپلیکشن، گوشی و یا ایمولاتور که استفاده می کنید باید گوگل پلی سرویس رو نصب داشته باشد.
لطفا از این مورد اطمینان حاصل فرمایید.
در ضمن پیشنهاد ما تست بر روی گوشی است چون ایمولاتورها می تواند خطای غیر واقعی ایجاد کند.
در صورتیکه مشکل شما حل نشد لطفا بفرمایید

**Comment by ghost1372** [comment]
سلام باتشکر از پاسخگویی
مشکل همچنان پابرجا هستش،درضمن توی مانیفست چرا پرمیشن خود اینترنت نیست؟
گوگل پلی سرویس هم نصب هست روی گوشی و اپدیته از این لحاظ مشکلی نیست کرش وقتی رخ میده که پوش نوتیفیکشن میخاد روی گوشی دریافت بشه

**Comment by mhahmadip** [comment]
سلام مجدد
دسترسی به اینترنت درمنیفست کتابخانه قرار دارد که با همان دستور گریدل به اپلیکیشن شما اضافه می شود
لطفا بفرمایید شما از کد نمونه استفاده کردید و یا بر روی برنامه خودتون در حال نصب هستید؟
. لطفا یک پروژه خالی(پروژه خالی اندروید استدیو) ایجاد کنید و آن را در پنل ایجاد کنید و مراحل را مجدد طی کنید دقت بفرمایید حداقل ای پی آی رو باید 16 قرار دهید.
در ضمن لطفا به بخش ساپورت سایت هم ایمیل بزنید تا دوستان راحت تر مشکل شما را حل کنند.
تشکر

**Comment by mhahmadip** [comment]
@ghost1372 
سلام دو ست گرامی
مشکل شم احل شد یا خیر
لطفا اگر مشکل پابرجاست بفرمایید
موفق باشید

**Comment by ghost1372** [comment]
مشک داره هنوز

**Comment by mhahmadip** [comment]
@ghost1372 
لطفا به آدرس
support@pushe.co
ایمیل بزنید تا دوستان پشتیبانی با شما تماس بگیرند و از طریق ریموت مشکل رو حل کنند.
با تشکر

(در نهایت راه حل در اینجا گذاشته خواهد شد)

**Comment by Hitexroid** [comment]
موقع دیپندنسی حتی با فیلترشکن هم این خطا رو میده

`Error:(41, 13) Failed to resolve: co.ronash.android:pushe-base:0.10.0
<a href="openFile:E:/AndroidStudioProjects/HitexStore2/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>`

**Comment by akramShokri** [comment]
@Hitexroid 
سلام
نسخه های قابل استفاده ی پوشه این ها هستند:

- 1.1.0
- 1.0.0
- 0.10.2
- 0.10.1
- 0.9.1
نسخه ی ۰.۱۰.۰ جزو این لیست نیست و به همین دلیل شما این مشکل را دارید.
پیشنهاد می کنیم که از آخرین نسخه یعنی ۱.۱.۰ استفاده کنید.
