### ISSUE TITLE
Keeps app packageName after obfuscation

### ISSUE THREAD

**Issue by ABPSoft** [pusheco/android-studio-sample#11]
<div dir='rtl'>

سلام
این مشکل چند روز وقت من رو گرفت و بعد متوجه شدم که مشکل از "پوشه" هست.

من از کتابخونه پوشه توی پروژه خودم استفاده کردم.
ولی باعث شد که اسامی کتابخانه هایی که استفاده کردم، نمایش داده بشن. در صورتی که من نمیخوام کسی بدونه از چه کتابخانه هایی استفاده کردم.
در فایل proguard مربوط به پوشه، این کد نوشته شده است.
</div>

```
    -keep class !**.R
    -keep class !**.R$* {
        <fields>;
    }
```

<div dir='rtl'>
که باعث تداخل میشه.

برای اینکه مشکل رو دقیقتر متوجه بشید، لینک زیر رو مشاهده کنید.
</div>

https://stackoverflow.com/questions/57893494/android-obfuscate-doesnt-change-package-name

**Comment by mahdi-malv** [comment]
Pushe has moved to [PushPole](https://push-pole.com) and issue has been fixed
