### ISSUE TITLE
 Program type already present: com.google.android.gms.location.places.zza

### ISSUE THREAD

**Issue by mahdifathi80** [pusheco/android-studio-sample#12]
Error: Program type already present: com.google.android.gms.location.places.zza
how i can solve this?

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام
خطایی که دارید به نظر میاد به خاطر تکراری بودن لایبرری لوکیشنه.

بررسی کنید از چه طرقی لایبرری Location به پروژه اضافه‌می‌شه؟
مثلا فایل JAR اضافه کردید یا ...
</div>

**Comment by mahdi-malv** [comment]
Inactive for 4 days. Feel free to reopen this issue if you still have this problem.
