### ISSUE TITLE
عدم دریافت پوش

### ISSUE THREAD

**Issue by ansaralghaem** [pusheco/android-studio-sample#13]
با عرض سلام
پوشه روی برنامه من رجیستر میشه و دستگاههای مورد نظر رو در لیست نصب میاره ولی امکان دریافت نوت برای برنامم فراهم نیست؟
کسی میدونه چرا؟

**Comment by mahdi-malv** [comment]
<div dir='rt'>
سلام.
آیا پوش تستی رو هم دریافت نمی‌کنه؟ از بخش نصب‌ها دیوایس رو پیدا کنید و اعلان تستی ارسال کنید.
اینترنت رو هم وصل کنید
</div>

**Comment by ansaralghaem** [comment]
با سلام مجدد
 تمام این کارها رو کردم
دستگاه رجیستر میشه ولی نوت تستی رو دریافت نمی کنه
بنده ۳ سال هست با پوشه کار می کنم و تا الان همچین چیزی ندیدم
این پوش آی دی یکی از دستگاه های رجیستر شده 
pid_a61d-627a-40
Samsung A30
ممنون میشم زودتر نتیجه رو اعلام کنید

**Comment by ansaralghaem** [comment]
من برناممم روزی چند هزار نصب داره لطفا
زودتر نتیجه رو به بنده اعلام کنید

**Comment by mahdi-malv** [comment]
Closed for Inactivity. Feel free to reopen the issue if the problem still exists.
