### ISSUE TITLE
Pushe is unresolved (Adding using .aar file)

### ISSUE THREAD

**Issue by andromaxiran** [pusheco/android-studio-sample#14]
<div dir='rtl'>
سلام
من فایل jar 
رو با موفقیت اضافه کردم و گریدل هم سینک شده اما 
        Pushe.initialize(this,true);
Pushe رو نمیشناسه!
</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام.
به نظر میاد که فایل لازم به درستی اضافه‌نشده. این لینک رو بررسی کنید.
</div>

https://stackoverflow.com/a/23326397/6678991

**Comment by andromaxiran** [comment]
سلام دوست عزیز
واقعا ازتون ممنونم مشکل حل شد و تو اکتیویتی پوشه ایمپورت شد به همه همکاران
و دوستان پیشنهاد کردم از سرویس پوشه استفاده کنن بخاطر پشتیبانی فوق العاده
قوی و معرفت شما ☺☺☺
سپاس🙏🙏🙏🙏

**Comment by andromaxiran** [comment]
سلام ببخشید یه کمک میخاستم
 تو لاگ کت میزنم pushe این ارور میده
E/Pushe: Initializing Pushe failed: co.ronash.pushe.task.b.a.b

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام.

انتظار می‌ره که  اینجور مشکلات پیش بیاد.
چون پوشه علاوه‌بر فایل ‌aar خودش نیاز به لایبرری‌های دیگه‌ای مثل فایربیس هم داره.
</div>

* `build.gradle` of Pushe:
```groovy
    implementation ('com.google.android.gms:play-services-location:16.0.0')
    implementation ('com.google.android.gms:play-services-ads:16.0.0')
    implementation ('com.evernote:android-job:1.2.6')
    implementation ('com.android.support:support-compat:26.0.0')
    implementation 'com.android.support:support-v4:26.1.0'
    implementation 'com.google.firebase:firebase-messaging:17.4.0'
    implementation ('com.google.android.gms:play-services-gcm:16.0.0')
```

<div dir='rtl'>
این لایبرری‌ها باید به گریدل اضافه‌بشن تا موارد لازم پوشه مهیا بشه.

**نکته**: کلا استفاده از این روش توصیه نمی‌شه بخاطر موارد زیر:
* مشکلات ClassNotFoundException و ...
* ممکنه که پروگارد هم مشکلاتی ایجاد کنه )تست نشده)

لذا بهتره که مشکل دانلود گریدل رو حل کنید و لایبرری رو از طریق گریدل به پروژه اضافه کنید.
</div>

**Comment by andromaxiran** [comment]
ممنون
گریدل ورژن چند رو دانلود کنم؟ که این لایبرری ها رو اضافه کنم
نسخه اندروید استودیو 2.3.2 هست

**Comment by mahdi-malv** [comment]
ترجیحا بروزترین‌ها رو دانلود و استفاده‌کنید.

**Comment by andromaxiran** [comment]
ببخشید من این لایبرری هارو اضافه کردم ولی خطاهای عجیبی(همونایی که فرمودید)
میارره ممنون میشم روش دانلود گریدل برای اندرویداستودیو2.3.2 رو بفرمایید. یا
لینک آموزش مورد تایید رو بفرستید چه ورژن گریدلی نیاز هست؟
