### ISSUE TITLE
Pushe id

### ISSUE THREAD

**Issue by alikhaniAli** [pusheco/android-studio-sample#15]
یک سری کاربر از قبل دارم چطوری میتونم پوشه آی دی ایجاد کنم خودم و بهشون بدم به صورت دستی؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام
ممنون که این سوالو پرسیدین.


پوشه‌آی‌دی یک شناسه‌ست که از طریق دستگاه بدست میاد.

**اندروید پایین‌تر از ۸:**
از شناسه‌ی **AndroidId** این مورد بدست میاد چون می‌تونه دستگاه رو یکتا کنه و تا ریست‌فکتوری تغییر نمی‌کنه.

**اندروید ۸ به بالا:**
از اندروید ۸ به بعد شناسه‌ی AndroidId در هر برنامه‌ متفاوت میشه و دیگه نمیشه باهاش دستگاه رو یکتا کرد و تمییز داد.
برای همین از **GoogleAdId** برای تمییز و یکتاسازی شناسه‌استفاده شد.

در صورتی که توسعه‌دهنده قابلیت دریافت **GoogleAdvertisingId رو در برنامه غیرفعال کنه** پوشه نمی‌تونه از اون استفاده کنه برای همین یک **شناسه‌ی رندوم** جنریت می‌کنه و اون رو ذخیره وبه سرور ارسال می‌کنه.

پس خلاصه‌این میشه که:
</div>

* **Android < 8**
  `PusheId = deviceId`
* **Android >= 8** and GoogleAdvetisingId **enabled**
  `PusheId = GoogleAdvertisingId`
* **Android >= 8** and GoogleAdvertisingId **disabled** (by app developer)
  `PusheId = Random`

<div dir='rtl'>

>  **آیا میشه پوشه‌آی‌دی رو دستی عوض کرد و یا جدید جنریت کرد؟**

 **خیر**.  این شناسه‌از آی‌دی های ثابت درست میشه و کاستوم نیست. شناسه‌ی کاستوم فیچر جدیده که در نسخه‌ی فعلی (۱.۶.۳) وجود نداره.
> **پوشه‌آی‌دی کی‌تغییر می‌کنه؟**
   * اگر دیوایس اندروید ۸ و یا بالاتر باشه و قابلیت استفاده از GoogleAdvertisingId ممکن نباشه در صورت نصب مجدد برنامه (یا پاک‌کردن دیتا) پوشه‌آ‌ی‌دی جدید ساخته میشه
   * اگر اندروید ۸ یا بالاتر باشه و ‌Ad id رو بشه استفاده کرد اما صاحب دیوایس اون رو از تنظیمات گوگل ریست کنه. در نصب بعدی شناسه تجدید میشه.

> ب**دست اومدن شناسه یعنی نصب پوشه ثبت شده؟** 

**خیر**. چون این‌ شناسه مستقل از فرآیند رجیستر کار می‌کنه و حتی بدون اینترنت هم میشه از اون استفاده کرد.
</div>
