### ISSUE TITLE
White icon while notification received to device

### ISSUE THREAD

**Issue by SkillsOn** [pusheco/android-studio-sample#16]
با سلام

وقتی نوتیفیکیشن می‌فرستم یه آیکون سفید در استاتوس‌بار دیده‌میشه.

ممنون میشم بدونم مشکل کجاست.
تشکر از سرویس خوبتون.

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام.

در اندروید ۸ یه قاعده برای آیکون نوتیفیکیشن ست شده اونم اینه که آیکون باید تماما سفید و بدون بکگراند باشه. در غیر اینصورت این مشکلی که گفتید پیش میاد.

پوشه در صورتی که برای نوتیفیکیشن آیکون ست نشه پیش‌فرض آیکون نوتیفیکیشن رو برابر آیکون برنامه‌ قرار می‌ده و در صورتی که آیکون برنامه تماما سفید و بدون بکگراند نباشه، یه مربع سفید دیده میشه.

در نظر داشته باشید مشکل برای اندروید ۸ به بالا پیش میاد و پایین‌تر مشکلی ندارن.

برای حل این مشکل باید هنگام ارسال نوتیفیکیشن براش آیکون مناسب ست کنید (از لیست پیش‌فرض کنسول یا خودتون مطابق استاندارد اندروید) و یا اینکه آیکون برنامتون پیش‌فرض این مورد رو رعایت کنه.

</div>

**Comment by rezaajori** [comment]
سلام وقت بخیر
سوال من مقداری متفاوت است
مشکل من در تمام نسخه های اندروید است نه صرفا اندروید 8
وقتی که نوتیفیشن ارسال میشود طبیعتا در استاتوز بار گوشی و در خود نوتیفیشن آیکن خود برنامه باید قرار بگیرد اما من وقتی نوتیفیشن ارسال میکنم یک مستطیل تقریبا خاکستری نشان داده میشود به جای آیکن اپ خودم. 
در منو هم گزینه ای برای تغییر ایکن اپ نیست.
آیا ایکن اپ از خود فایل apk خوانده میشود ؟
![b3280170-71db-43af-8332-29751b4908b3](https://user-images.githubusercontent.com/56784616/67156415-04222280-f32b-11e9-9d5f-759a9ceb3091.jpg)
![f5cb522c-dfa7-4886-84b9-fce78160024f](https://user-images.githubusercontent.com/56784616/67156416-04222280-f32b-11e9-9205-a31ef97fa115.jpg)

**Comment by rezaajori** [comment]
![df](https://user-images.githubusercontent.com/56784616/67156500-1c467180-f32c-11e9-9419-3d7aff5e478c.jpg)
تصویری از خطای ذکر شده.

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

آیکونی که توی کنسول دیده‌میشه (یا دیده باید بشه) ربطی به SDK نداره و از مایکت‌ها دانلود میشه (اگر اپ در مارکت باشه آیکون باید نشون‌داده بشه).

اما دلیل اینکه آیکون سفیدشده به این دلیله:

طبق [این سوال توی ‌استک‌اورفلو](https://stackoverflow.com/questions/30795431/android-push-notifications-icon-not-displaying-in-notification-white-square-sh) برای اینکه آیکون درست نمایش‌داده باشه باید تماما سفید و بدون‌بکگراند (یا بکگراند transparent) باشه. در غیر اینصورت آیکون بعد از تبدیلی که اندروید نشون می‌ده سفیدمیشه (فقط برای اندروید ۵ به بالا این مورد پیش میاد).

>‌ آیکون هنگام نمایش اعلان از SDK خونده میشه
>‌آیکون هنگام ساخت اپ توی کنسول از مارکت‌ها خونده میشه

## راه‌حل‌های موجود برای رفع مشکل

* **آیکون‌ برنامه پیش‌فرض استاندارد باشه**. یعنی سفید و بدون بکگراند باشه.

در این صورت آیکون بعد از تبدیل هم سالم دیده میشه.

* **آیکون جایگزین**ی طراحی کنید و توی برنامه بذارید با ویژگی‌های زیر:
     - سفید و بدون بکگراند
    - با نام: **ic_silhouette**

در این صورت اگر قرار بود آیکون سفید بشه پوشه دنبال این ایکون با نام ذکر شده می‌گرده و اون رو استفاده می‌کنه.

* پیش‌فرض خودتون **آیکون‌دیگه‌**ای رو برای اعلان انتخاب کنید.

مثلا یکی از آیکون‌های توی کنسول رو ست کنی. مثل آیکون زنگوله. در این صورت آیکون درست نمایش داده‌میشه. اما آیکون برنامه‌ی شما نیست.

</div>

**Comment by mahdi-malv** [comment]
Feature exists in **Pushe 1.6.3**

**Comment by rezaajori** [comment]
سفید و بدون بکگراند یعنی یک تصویر
با بکگراند
transparent
که سایر موارد با رنگ سفید در تصویر طراحی شوند ؟

و سایزش ؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

نمی‌دونم باید داکیومنت اندروید رو بخونید برای آیکون استاندارد

</div>

[Google design guide line](https://material.io/design/iconography/#grid-keyline-shapes)
