### ISSUE TITLE
ایجاد پلاگین در نیتیو اسکریپت برای استفاده از پوشه

### ISSUE THREAD

**Issue by mmostafaf** [pusheco/android-studio-sample#18]
سلام دوستان
ما یه برنامه توی نیتیو اسکریپت نوشتیم که برای استفاده از نوتیفیکیشن میخواهیم از پوشه استفاده کنیم اما پوشه اون رو ساپرت نمی کنه
ایا راهی میشناسید که بتونیم براش یه پلاگین بنویسیم تا پوشه بتون اون رو هم ساپرت کنه

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام.
کلا برای اینکه پلاگینی برای پوشه نوشته بشه نیازی نیست از سمت پوشه کاری انجام بشه.
خود فریم‌ورک امکانات لازم رو برای استفاده از لایبرری نیتیو در اختیار می‌ذاره.

تو کیس شما هم، باید داکیومنت نیتیو اسکریپت رو بخونید ببینید چه کارایی باید انجام بدید:

* لایبرری گریدل پوشه رو مطابق داکیومنت‌ها اضافه‌کنید
* اپ رو توی کنسول ثبت کنید و مانیفست رو کپی کنید
* مانیفست رو مطابق راهنمای کنسول در AndroidManifest قرار بدید

[این لینک](https://stackoverflow.com/questions/53617507/how-to-include-available-gradle-library-in-nativescript-angular-app) می‌تونه مفید باشه. می‌تونید توی نیتیو اسکریپت گریدل لایبرری هم داشته باشید و پشتیبانی میشه. لذا خیلی کاری نداره.
</div>

**Comment by mmostafaf** [comment]
من سوالم اینه که نوشتنش سخته که دوستان پوشه این فیچر رو اضافه نمی کنن چون اونها برای فریم ورک های مختلف نوشتن نوشتن این قطعا براشون سخت نیست البته اگر این یه مورد خاص نباشه

**Comment by mahdi-malv** [comment]
سلام

فکر نمی‌کنم سخت باشه.

اگر از سمت بخش محصول تشخیص‌داده بشه که لازمه این فریم‌ورک هم پشتیبانی بشه پلاگینش طراحی خواهد شد.

فعلا این پلاگین توی تسک‌ها نیست.

**Comment by mmostafaf** [comment]
پس یه راهنمایی دقیق تر بفرمایید که دقیقا از کجا باید شروع کنیم به چه مسیری رو بریم و به کجا برسیم
