### ISSUE TITLE
What is the URL of notification server when sending and receiving

### ISSUE THREAD

**Issue by antiowl** [pusheco/android-studio-sample#19]
<div dir='rtl'>

سلام
می‌خواستم بدونم که پوشه از چه طریقی نوتیفیکیشن‌ها رو ارسال می‌کنه؟ برای این که اون رو در white list قرار بدیم.

</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام



ریکوئست به از طریق API همون آدرسیه که ذکر کردید، اما دریافت پیام اعلان توی دیوایس مورد نظر از طریق فایربیس انجام می‌شه و پوشه کارش اینه که یه پیام به فایربیس می‌ده که به این دستگاه با این اطلاعات این پیام ارسال بشه و فایربیس اون رو ارسال می‌کنه.

ارسال و دریافت پیام‌های نوتیفیکیشن در دستگاه از طریق ‌socketی که Google play services در دستگاه برای ارتباط با فایربیس باز می‌کنه انجام می‌شه و اگر بخواد ادرس اون رو توی white listتون قرار بدید باید ببینید که آدرس اون socket چی هست.



فکر می‌کنم فقط یک آدرس نباشه و آدرس‌های مختلفی باشن. مثلا توی دستگاه من برنامه‌های گوگل با آدرس
1e100.net 
ارتباط برقرار می‌کنن
من این مورد رو با نصب برنامه‌ی packet capture فهمیدم
</div>
