### ISSUE TITLE
Firebase version conflict

### ISSUE THREAD

**Issue by antiowl** [pusheco/android-studio-sample#20]
<div dir='rtl'>
سلام
من باید این خط رو به گریدل برای استفاده از سرویس فایربیس اضافه کنم
</div>

`implementation 'com.google.firebase:firebase-core:17.2.0'`

<div dir='rtl'>
اما این ارور رو می‌گیرم:
</div>

```
ERROR: In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.1.
0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.google.firebase:firebase-messaging:17.4.0 -> com.google.firebase:firebase-iid@[17.1.0], but fire
base-iid version was 19.0.0.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto com.google.firebase:firebase-core@17.1.0
-- Project 'app' depends onto com.google.firebase:firebase-analytics@{strictly 17.1.0}
-- Project 'app' depends onto com.google.firebase:firebase-iid@{strictly 19.0.0}
-- Project 'app' depends onto co.ronash.android:pushe-base@1.6.3
-- Project 'app' depends onto co.ronash.android:pushe-base@{strictly 1.6.3}
-- Project 'app' depends onto com.google.firebase:firebase-core@{strictly 17.1.0}
-- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@{strictly 17.1.0}
-- Project 'app' depends onto com.google.firebase:firebase-messaging@{strictly 17.4.0}
```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام

پوشه برای ارسال و دریافت پیام از دستگاه به سرور از سرویس **Firebase messaging** استفاده می‌کنه.
نسخه‌ی 1.6.3 از نسخه‌ی 17.4.0 این لایبرری استفاده می‌کنه.

در صورتی که یکی از لایبرری‌های شما با این نسخه‌ تداخل داشت، می‌تونید کتابخونه‌هایی که پوشه اضافه‌کرده رو override کنید.

توی کیسی که شما ذکر کردید در صورتی که لایبرری Firebase messaging رو خودتون اضافه کنید و نسخه‌ی **19.0.0** رو برای ورژن لایببری قرار بدید، این مورد حل خواهد شد (البته لازم به ذکره که **نسخه‌ی 19.0.0 از AndroidX استفاده می‌کنه و پروژتون باید از AndroidX استفاده کنه و نه support library**.)
</div>

Add to `build.gradle`:

```
implementation 'com.google.firebase:firebase-core:17.2.0'
implementation "com.google.firebase:firebase-messaging:19.0.0"
```

<div dir='rtl'>

اطلاعات بیشتر درمورد نسخه‌های کتابخانه‌های فایربیس در [این لینک](https://firebase.google.com/support/release-notes/android).
</div>
