### ISSUE TITLE
مستندات جدید بروی وب سایت با آخرین نسخه مطابقت ندارند تابع setNotificationListener

### ISSUE THREAD

**Issue by adelhoss** [pusheco/android-studio-sample#22]
با سلام
متاسفانه مستندات شما با آخرین نسخه یعنی
2.0.2
مطابقت ندارند
برای مثال تابع : setNotificationListener
در نسخه 2.0.2 وجود ندارد
لطفا راهنمایی کنید
در ضمن نسخه های پیشنین گیت هاب شما
بخش دریافت اطلاعات json 
هم وجود داشت
اما در این نسخه ی فعلی گیت هاب اشاره ایی به این موضوع نشده
دقیقا منظورمون این هست 
http://docs.pushe.co/docs/android-studio/studio-listener
رویدادهای ناتفیکیشن رو لطفا در گیت هاب وارد کنید
با تشکر

**Comment by adelhoss** [comment]
پروژه ی ما متوقف شده و منتظر کمک پشتیبانان عزیز پوشه هستیم

**Comment by fsghasemi** [comment]
سلام خدمت شما 
خیلی بابت مشکل پیش اومده عذرخواهی میکنم. امروز داکیومنت آپدیت میشه. 
شما برای اینکه از notification listener استفاده کنید دستور زیر رو باید بنویسید
Pushe.getPusheService(PusheNotification.class).setNotificationListener

با سپاس از همراهی شما

**Comment by adelhoss** [comment]
با سلام
لطفا بخش نمونه ی گیت هاب رو خواهش می کنیم دریافت 
json
رو توضیح بدین قبلا خود جی سان دریافت می شد
الان چیزی که دریافت میشه یک
map
هست
با سپاس از لطفتون

**Comment by adelhoss** [comment]
لطفا خواهش می کنیم مانند سایر نسخه ها هم مستندات بروزرسانی بشه و هم پروژه ی مثالی 
گیت هاب رو هم
بروزرسانی کنید بخش رویدادهای ناتیفیکیشن
با سپاس
وب سایتتون هم قدری مشکل داره
با اکانت گوگل نمی تونیم لاگین کنیم
از 
web api
هم که پوش ارسال می کنیم
خطای 
bad gateway 502
برگشت داده میشه
واقعا تیم ما تحت فشاره

**Comment by fsghasemi** [comment]
سلام 
پروژه نمونه در گیت هاب بروزرسانی شده و قسمت رویدادهای نوتیفیکشن هم در نمونه گیت هاب وجود داره. در مورد قسمتی که فرمودید قبلا جیسون بوده و الان مپ شده هم باید خدمتتون عرض کنم که جیسون رو اگه به صورت کلید و مقدار نگاه کنیم الان هم مپ همون کار رو انجام میده یعنی فیلد های جیسون میشن کلید های مپ

با سپاس از همراهی شما

**Comment by adelhoss** [comment]
با سلام
هرچقدر گشتیم تغییراتی مشاهده نکردیم
مگر قرار نبوده از کلاس
application
ارث بری کنیم و در اونجا 
Listener
ها رو فراخوانی کنیم؟
در فایل
AndroidManifest
کلاسی مبنی بر ارث بری از کلاس 
Application
دیده نشد 
ممنونتون میشیم اگر دقیقا اشاره کنید که در کدوم فایل تغییرات ایجاد شدن

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام.
خیلی فورس نیست که توی کلاس اپلیکیشن قرار داشته باشه.    
برای اینکه اپلیکیشن توی بکگراند هم بتونه این کالبک‌ها رو فراخونی کنه نیاز هست که کالبک توی کلاسی اضافه بشه که توی بکگراند هم فراخونی میشه. خب می‌دونیم که کلاس اپلیکیشن این اتفاق براش می‌افته، اما کلاس‌هایی مثل اکیتیوتی‌ها نه. اونا زمانی فراخونی میشن که توی صفحه باز بشن و لایف‌سایکلشون شروع بشه.    
توی مثال هم کالبک توی اکیتیویتی اصلی اضافه شده، بدین معنی که فقط زمانی کالبک‌ها فراخونی بشن که اکتیویتی در حال اجراس.

مثال بدین صورت هست:

</div>

```java
Pushe.getPusheService(PusheNotification.class).setNotificationListener(new PusheNotificationListener() {
            @Override
            public void onNotification(@NonNull NotificationData notification) {
                addText(status, "Listener on receiving notification triggered");
                scroll.fullScroll(View.FOCUS_DOWN);
            }

            @Override
            public void onCustomContentNotification(@NonNull Map<String, Object> customContent) {
                addText(status, "Listener on receiving notification with custom content triggered");
                scroll.fullScroll(View.FOCUS_DOWN);
            }

            @Override
            public void onNotificationClick(@NonNull NotificationData notification) {
                addText(status, "Listener on clicking on notification triggered");
                scroll.fullScroll(View.FOCUS_DOWN);
            }

            @Override
            public void onNotificationDismiss(@NonNull NotificationData notification) {
                addText(status, "Listener on dismissing notification triggered");
                scroll.fullScroll(View.FOCUS_DOWN);
            }

            @Override
            public void onNotificationButtonClick(@NonNull NotificationButtonData button, @NonNull NotificationData notification) {
                addText(status, "Listener on clicking on notification button triggered");
                scroll.fullScroll(View.FOCUS_DOWN);
            }
        });
```

<div dir='rtl'>

بخش مورد نظر شما هم ‌`onCustomContentReceived` هست که `Map<String, Object>` میده.

</div>

```java
@Override
 public void onCustomContentNotification(@NonNull Map<String, Object> customContent) {
   // Gives a map of (String, Object) or (String, Any) having the custom content
 }
```

<div dir='rtl'>

> چرا `Object` ؟

در صورتی که جیسون دلخواه nested باشه، این مپ می‌تونه مقدار آبجکتش کست بشه به Map دوباره.

</div>

```java
Map<String, Object> result;

Object o = result.get("keyWithNestedValue");

if (o instanceof Map) {
   String result = ((Map<String, Object) o).get("aNestedKey");
}
```
<div dir='rtl'>

> چرا `مپ`؟

داخل sdk از مپ برای ساخت جیسون‌ها استفاده شده و برای همین چیزی که برای کالبک ارسال میشه مپ هست. تبدیلش به جیسون یا استرینگ هم خیلی سخت نیست.

</div>
