### ISSUE TITLE
sendNotificationToUser by CustomId

### ISSUE THREAD

**Issue by saeedhosseini** [pusheco/android-studio-sample#23]
<div dir='rtl'>

سلام
کد زیر را برای ارسال پوش نوتیفیکشن زدم ولی کار نمی کند
</div>

```java
 btn_broken.setOnClickListener(e->{
            if (Pushe.isRegistered()){
                Log.d(TAG, "is registerd");
                Log.d(TAG, Pushe.getCustomId());
                UserNotification userNotification = UserNotification.withCustomId(Pushe.getCustomId());
                userNotification.setTitle("title1");
                userNotification.setContent("content1");
                Log.d(TAG, userNotification.toString());
                    (Pushe.getPusheService(PusheNotification.class))
                            .sendNotificationToUser(userNotification);
            }else {
                Log.d(TAG, "no registerd");
            }
        });
```

<div dir='rtl'>

زمانی که ریجیستر میشه کاستوم ایدی همه برابر 10 میکنم
تو لاگ هم ده نشان میده 
ولی نوتیفکیشن نه برای خود دستگاه و همینطور دستگاه دیگر که اپ را نصب دارند نمیره

</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

در حال حاضر ارسال **DeviceToDevice** سمت سرور فانکشن نداره و بزودی به امکانات اضافه خواهد شد.

با تشکر

</div>

**Comment by saeedhosseini** [comment]
> سلام
> 
> در حال حاضر ارسال **DeviceToDevice** سمت سرور فانکشن نداره و بزودی به امکانات اضافه خواهد شد.
> 
> با تشکر

ممنون
فقط بزودی یعنی چند وقت دیگه
چون پروژه خیلی وابسته به این موضوع هست
تو این هفته سمت سرور زده میشود؟
