### ISSUE TITLE
"pushe" dependency not found

### ISSUE THREAD

**Issue by rezaiyan** [pusheco/android-studio-sample#6]
Hi, this dependency `compile 'co.ronash.android:pushe-base:1.3.0'` not found
i should changed version to `1.2.0`
so gradle be sync

**Comment by ghost1372** [comment]
سلام نسخه 1.3.0 توی مخازن جی سنتر و... موجود نیست نسخه آفلاینش هم ریلیز نشده هنوز احتمالا اشتباه چاپی بوده

**Comment by rezaiyan** [comment]
Thanks for your responsibility.
please fix it in code.
