### ISSUE TITLE
عدم دریافت پیام

### ISSUE THREAD

**Issue by ghost1372** [pusheco/android-studio-sample#7]
سلام من از پوشه توی تلگرام شخصی سازی شده خودم استفاده کردم وقتی اجراش میکنم بدون مشکل گوشی توی پوشه ثبت میشه و تعداد کاربران رو هم ثبت میکنه ولی هر پوشی که میفرستم توی گوشی دریافت نمیشه مشکل از کجاس؟

**Comment by akramShokri** [comment]
لطفا به پشتیبانی پوشه ایمیل بزنید.
