### ISSUE TITLE
قادر به دریافت ایونت کلیک و غیره روی نوتیفیکیشن نیستم

### ISSUE THREAD

**Issue by pouyadanesh** [pusheco/android-studio-sample#9]
در منیفست دقیقا همان چیزی که توی پروژه شماست من کپی کردم
اما در کلاس NotifBroadcastReceiver نمیرود
لطفا راهنمایی کنید
فکر می کنم مشکل از applicationId در منیفست است که نمیدونم چه چیزی را باید آنجا جایگزین کنم

با تشکر

**Comment by mzmatin** [comment]
نسخه‌ی اندرویدی که دارید تست می‌کنید رو می‌فرمایید؟

**Comment by pouyadanesh** [comment]
حل شد دوست عزیز 
خسته نباشید
مشکلش اسم پکیج بود که باید توی اندروید منیفست قرار می گرفت
